# NumPy 

- NumPy (or Numpy) is a Linear Algebra Library for Python, 
- Almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
- Numpy is also incredibly fast, as it has bindings to C libraries. 
- check out this [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially come in two flavors: 
- vectors and 
- matrices. 

Vectors are strictly 1-d arrays and matrices are 2-d (a matrix can still have one row or one column, like a Vector).


## Creating NumPy Arrays

In [6]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,110,17)

array([  0,  17,  34,  51,  68,  85, 102])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))
#np.zeros((2,2,2))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [18]:
np.random.rand(2)

array([0.74404374, 0.21712139])

In [19]:
np.random.rand(5,5)

array([[0.15017839, 0.73443962, 0.74066874, 0.57786497, 0.32572368],
       [0.5757958 , 0.93003722, 0.11565705, 0.94499155, 0.38290312],
       [0.48772816, 0.6929886 , 0.99728904, 0.83488005, 0.08654756],
       [0.0852247 , 0.3424157 , 0.9852936 , 0.33388745, 0.93375459],
       [0.41031364, 0.78136037, 0.14203325, 0.17661253, 0.54479812]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(2)

array([ 0.99189847, -0.32926517])

In [21]:
np.random.randn(5,5)

array([[-0.89908612,  0.71751915, -0.25463409, -1.08088402, -0.27471665],
       [ 1.23122581, -1.23061902, -0.369657  , -0.09387555,  0.91399027],
       [ 0.31094986,  0.73922004,  0.99312674, -0.20336848,  0.78960059],
       [-0.03401168,  1.25216352,  1.82685128, -0.74626423, -0.9194539 ],
       [ 0.14801831, -0.08892354, -0.09156909, -1.5110337 , -2.03315839]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100)

59

In [23]:
np.random.randint(1,100,10)

array([34, 95, 11, 20, 99, 33, 40, 88, 31,  4])

## Array Attributes and Methods

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([27, 48,  5, 21, 46,  4,  2, 27, 38, 20])

## Reshape
Returns an array containing the same data with a new shape.

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([27, 48,  5, 21, 46,  4,  2, 27, 38, 20])

In [29]:
ranarr.max()

48

In [30]:
ranarr.argmax()

1

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmin()

6

## Shape

Shape is an attribute that arrays have (not a method):

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [2]:
arr.dtype

NameError: name 'arr' is not defined